import { Listing, Seller, Category } from './types';

export const mockSellers: Record<string, Seller> = {
  'sarah-tokyo': {
    id: 'sarah-tokyo',
    name: 'Sarah - Tokyo Collector',
    avatar: 'ST',
    rating: 5.0,
    totalSales: 53,
    verified: true,
    joinedDate: '2022-03-15',
    specialization: 'Limited Editions',
  },
  'mike-hunter': {
    id: 'mike-hunter',
    name: 'Mike - Labubu Hunter',
    avatar: 'MH',
    rating: 4.9,
    totalSales: 38,
    verified: true,
    joinedDate: '2022-07-20',
    specialization: 'Rare Finds',
  },
  'jenny-dealer': {
    id: 'jenny-dealer',
    name: 'Jenny - Professional Dealer',
    avatar: 'JD',
    rating: 4.8,
    totalSales: 127,
    verified: true,
    joinedDate: '2021-11-05',
    specialization: 'Authentication Expert',
  },
  'alex-collector': {
    id: 'alex-collector',
    name: 'Alex - Series Completionist',
    avatar: 'AC',
    rating: 4.9,
    totalSales: 45,
    verified: true,
    joinedDate: '2022-05-10',
  },
};

export const mockListings: Listing[] = [
  {
    id: 'pirate-series-1',
    title: 'Pirate Labubu - Series 1',
    description: 'Mint condition Pirate Series Labubu with original packaging and accessories. This rare piece features the iconic pirate hat and treasure chest. Perfect for collectors looking to complete their series.',
    price: 85,
    image: 'pirate',
    images: ['pirate', 'pirate', 'pirate'],
    condition: 'mint',
    seller: mockSellers['sarah-tokyo'],
    series: 'Pirate Series',
    year: 2023,
    isLimited: false,
    isFeatured: true,
    status: 'active',
    verificationStatus: 'verified',
    views: 234,
    favorites: 18,
    listedDate: '2025-10-10',
    category: 'Series Collection',
  },
  {
    id: 'knight-series-1',
    title: 'Knight Labubu - Series 1',
    description: 'Limited edition Knight Labubu in excellent condition. Comes with shield and sword accessories. Part of the exclusive medieval collection.',
    price: 92,
    image: 'knight',
    images: ['knight', 'knight', 'knight'],
    condition: 'excellent',
    seller: mockSellers['sarah-tokyo'],
    series: 'Medieval Series',
    year: 2023,
    isLimited: true,
    isFeatured: true,
    status: 'active',
    verificationStatus: 'verified',
    views: 312,
    favorites: 24,
    listedDate: '2025-10-12',
    category: 'Limited Edition',
  },
  {
    id: 'limited-black-crown',
    title: 'Limited Edition Black Crown',
    description: 'Ultra-rare Limited Edition Black Crown Labubu. One of only 500 pieces worldwide. Comes with certificate of authenticity and special display case.',
    price: 285,
    originalPrice: 350,
    image: 'black-crown',
    images: ['black-crown', 'black-crown', 'black-crown'],
    condition: 'mint',
    seller: mockSellers['jenny-dealer'],
    series: 'Royal Collection',
    year: 2024,
    isLimited: true,
    isFeatured: true,
    status: 'active',
    verificationStatus: 'verified',
    views: 892,
    favorites: 67,
    listedDate: '2025-10-08',
    category: 'Limited Edition',
  },
  {
    id: 'pink-crown',
    title: 'Labubu Pink Crown Edition',
    description: 'Adorable Pink Crown Labubu from the Royal Series. Excellent condition with all original accessories including crown and scepter.',
    price: 145,
    image: 'pink-crown',
    images: ['pink-crown', 'pink-crown', 'pink-crown'],
    condition: 'excellent',
    seller: mockSellers['mike-hunter'],
    series: 'Royal Collection',
    year: 2024,
    isLimited: false,
    isFeatured: true,
    status: 'active',
    verificationStatus: 'verified',
    views: 445,
    favorites: 32,
    listedDate: '2025-10-14',
    category: 'Series Collection',
  },
  {
    id: 'winter-series-2023',
    title: 'Winter Series Labubu 2023',
    description: 'Mint condition Winter Series Labubu with snowflake accessories and winter coat. Rare seasonal release.',
    price: 250,
    image: 'winter',
    images: ['winter', 'winter', 'winter'],
    condition: 'mint',
    seller: mockSellers['sarah-tokyo'],
    series: 'Winter Series',
    year: 2023,
    isLimited: true,
    isFeatured: false,
    status: 'active',
    verificationStatus: 'verified',
    views: 567,
    favorites: 43,
    listedDate: '2025-10-05',
    category: 'Seasonal',
  },
  {
    id: 'halloween-limited',
    title: 'Halloween Limited Edition',
    description: 'Rare Halloween edition with original packaging. Features glow-in-the-dark elements and spooky accessories.',
    price: 400,
    image: 'halloween',
    images: ['halloween', 'halloween', 'halloween'],
    condition: 'mint',
    seller: mockSellers['jenny-dealer'],
    series: 'Halloween Collection',
    year: 2023,
    isLimited: true,
    isFeatured: false,
    status: 'active',
    verificationStatus: 'verified',
    views: 1203,
    favorites: 89,
    listedDate: '2025-10-01',
    category: 'Seasonal',
  },
  {
    id: 'artist-collaboration',
    title: 'Artist Collaboration Special',
    description: 'Special artist collaboration piece with unique design. Limited run of 300 pieces. Includes signed certificate.',
    price: 600,
    image: 'artist',
    images: ['artist', 'artist', 'artist'],
    condition: 'mint',
    seller: mockSellers['alex-collector'],
    series: 'Artist Collaborations',
    year: 2024,
    isLimited: true,
    isFeatured: false,
    status: 'active',
    verificationStatus: 'verified',
    views: 723,
    favorites: 54,
    listedDate: '2025-09-28',
    category: 'Special Edition',
  },
  {
    id: 'vintage-2019',
    title: 'Vintage 2019 Original Release',
    description: 'Original 2019 release in excellent condition. A piece of Labubu history for serious collectors.',
    price: 150,
    image: 'vintage',
    images: ['vintage', 'vintage', 'vintage'],
    condition: 'excellent',
    seller: mockSellers['mike-hunter'],
    series: 'Original Series',
    year: 2019,
    isLimited: false,
    isFeatured: false,
    status: 'active',
    verificationStatus: 'verified',
    views: 389,
    favorites: 27,
    listedDate: '2025-10-11',
    category: 'Vintage',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'blind-boxes',
    name: 'Blind Boxes',
    image: 'blind-box',
    count: 145,
  },
  {
    id: 'artist-collab',
    name: 'Artist Collabs',
    image: 'artist',
    count: 23,
  },
  {
    id: 'vintage-finds',
    name: 'Vintage Finds',
    image: 'vintage',
    count: 67,
  },
  {
    id: 'rare-editions',
    name: 'Rare Editions',
    image: 'rare',
    count: 34,
  },
];

export const getFeaturedListings = () => mockListings.filter(l => l.isFeatured);
export const getListingById = (id: string) => mockListings.find(l => l.id === id);
export const getSellerListings = (sellerId: string) =>
  mockListings.filter(l => l.seller.id === sellerId);
